package com.unosoft.ecomercialapp.entity.Cotizacion

import java.math.BigDecimal
import java.util.*

class CotizacionCabDTO : ArrayList<CotizacionCabDTOItem>()

data class CotizacionCabDTOItem(
    val centrO_COSTO: String,
    val codigO_CPAGO: String,
    val codigO_EMPRESA: String,
    val codigO_MONEDA: String,
    val codigO_SUCURSAL: String,
    val codigO_VENDEDOR: String,
    val codigO_VENDEDOR_ASIGNADO: String,
    val comision: Double,
    val competencia:String?,
    val contacto: String,
    val correlativo: String,
    val costo:String?,
    val detCotizacion:String?,
    val diaS_ENTREGA: Int,
    val diaS_ENTREGA2: Int,
    val direccion:String?,
    val emaiL_CONTACTO: String,
    val estado:String?,
    val fechA_AUTORIZACION:String?,
    val fechA_COTIZACION: String,
    val fechA_CREACION:String?,
    val fechA_ENTREGA: String,
    val fechA_MODIFICACION: String,
    val iD_CLIENTE: Int,
    val iD_CLIENTE_FACTURA: Int,
    val iD_COTIZACION: Int,
    val iD_COTIZACION_PARENT:String?,
    val iD_OPORTUNIDAD:String?,
    val iD_PROYECTO:String?,
    val importE_DESCUENTO: Double,
    val importE_IGV: Double,
    val importE_ISC: Double,
    val importE_STOT: Double,
    val importE_TOTAL: Double,
    val lugaR_ENTREGA: String,
    val motivO_PERDIDA:String?,
    val motivo: String,
    val noM_MONEDA:String?,
    val notA_PERDIDA:String?,
    val numerO_COTIZACION: String,
    val numerO_OCLIENTE: String,
    val observacioN2: String,
    val observacion: String,
    val persona: String,
    val porcentajE_DESCUENTO: Double,
    val porcentajE_IGV: Double,
    val redondeo: String,
    val ruc: String,
    val separaR_STOCK:String?,
    val sucursal: String,
    val swT_VISADO:String?,
    val telefonos: String,
    val tipO_CAMBIO: Double,
    val tipO_CLIENTE:String?,
    val tipO_DSCTO:String?,
    val tipO_ENTREGA: String,
    val tipO_FECHA_ENTREGA: String,
    val usuariO_AUTORIZA:String?,
    val usuariO_CREACION:String?,
    val usuariO_MODIFICACION: String,
    val usuario:String?,
    val validez: String,
    val valoR_VENTA: Double
)